// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWvUmHYJql8QPCVTnKLOECtJrnjo87yU',
    appId: '1:1004286842383:web:31fd0a5799b01b80c0757a',
    messagingSenderId: '1004286842383',
    projectId: 'flutter-tcc-example',
    authDomain: 'flutter-tcc-example.firebaseapp.com',
    storageBucket: 'flutter-tcc-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbT7TgaCgH4lk7XGatSQQfKVLj3HmGSqI',
    appId: '1:1004286842383:android:3292d5491e2a6c50c0757a',
    messagingSenderId: '1004286842383',
    projectId: 'flutter-tcc-example',
    storageBucket: 'flutter-tcc-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk3hPm_cJ9v63FpHs3WF1J5M6zDuiFeuU',
    appId: '1:1004286842383:ios:b7db4eee8100a730c0757a',
    messagingSenderId: '1004286842383',
    projectId: 'flutter-tcc-example',
    storageBucket: 'flutter-tcc-example.appspot.com',
    iosBundleId: 'com.example.flutterTcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk3hPm_cJ9v63FpHs3WF1J5M6zDuiFeuU',
    appId: '1:1004286842383:ios:06a661006064de51c0757a',
    messagingSenderId: '1004286842383',
    projectId: 'flutter-tcc-example',
    storageBucket: 'flutter-tcc-example.appspot.com',
    iosBundleId: 'com.example.flutterTcc.RunnerTests',
  );
}
